apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::422547873716:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-18FJH6SSQU7PI
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::422547873716:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-30T14:34:46Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1824"
  uid: 17a0ff0f-7f62-4e3b-8039-190be341a594
